services:
  - type: web
    name: smart-attendance-system
    runtime: python
    healthCheckPath: /
    buildCommand: pip install -r smart_attendance_system/requirements-render.txt
    startCommand: gunicorn --chdir smart_attendance_system wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
